library SYNC_ScreenLayout_Filter;

// 「画面レイアウト」フィルターのAviUtl2 DLL境界。

{$ALIGN 8}

uses
  AviUtl2FilterTypes in 'Lib\AviUtl2\AviUtl2FilterTypes.pas',
  PluginFilterTable in 'Lib\AviUtl2\PluginFilterTable.pas',
  PluginFilterContextManager in 'Lib\AviUtl2\PluginFilterContextManager.pas',
  ScreenLayoutFilterPlugin in 'Source\PlacementPlugin\ScreenLayoutFilterPlugin.pas',
  ScreenLayoutFrameCapture in 'Source\PlacementPlugin\ScreenLayoutFrameCapture.pas',
  ScreenLayoutFilterContext in 'Source\PlacementPlugin\ScreenLayoutFilterContext.pas',
  ScreenLayoutPluginDocument in 'Source\PlacementPlugin\ScreenLayoutPluginDocument.pas',
  ScreenLayoutEditorHost in 'Source\PlacementPlugin\ScreenLayoutEditorHost.pas',
  TextRendererSkiaBootstrap in 'Lib\TextRenderer\TextRendererSkiaBootstrap.pas',
  TextRendererTypes in 'Lib\TextRenderer\TextRendererTypes.pas',
  TextRenderer in 'Lib\TextRenderer\TextRenderer.pas',
  TextRendererSkiaRuntime in 'Lib\TextRenderer\TextRendererSkiaRuntime.pas',
  TextRendererSkia in 'Lib\TextRenderer\TextRendererSkia.pas',
  VectArtDarkPopupMenu in 'Lib\DarkMenu\VectArtDarkPopupMenu.pas',
  VectArtDarkMenuGroup in 'Lib\DarkMenu\VectArtDarkMenuGroup.pas',
  ShortcutAction in 'Lib\ShortcutAction\ShortcutAction.pas',
  HorizontalTrackBarRenderer in 'Lib\HorizontalTrackBar\HorizontalTrackBarRenderer.pas',
  HorizontalTrackBarControl in 'Lib\HorizontalTrackBar\HorizontalTrackBarControl.pas',
  ScreenLayoutMainForm in 'Source\Shell\ScreenLayoutMainForm.pas' {MainForm},
  ScreenLayoutObjectContextMenu in 'Source\Shell\Menus\ScreenLayoutObjectContextMenu.pas',
  ScreenLayoutTextContextMenu in 'Source\Shell\Menus\ScreenLayoutTextContextMenu.pas',
  ScreenLayoutPathContextMenu in 'Source\Shell\Menus\ScreenLayoutPathContextMenu.pas',
  ScreenLayoutTransformContextMenu in 'Source\Shell\Menus\ScreenLayoutTransformContextMenu.pas',
  ScreenLayoutArrangementContextMenu in 'Source\Shell\Menus\ScreenLayoutArrangementContextMenu.pas',
  ScreenLayoutEditActionsUI in 'Source\Shell\Toolbars\ScreenLayoutEditActionsUI.pas',
  ScreenLayoutStrokeStyleCombo in 'Source\ObjectProperties\Geometry\ScreenLayoutStrokeStyleCombo.pas',
  ScreenLayoutLineToolbar in 'Source\Shell\Toolbars\ScreenLayoutLineToolbar.pas',
  ScreenLayoutLineToolbarOperations in 'Source\Shell\Toolbars\ScreenLayoutLineToolbarOperations.pas',
  ScreenLayoutTextToolbarOperations in 'Source\Shell\Toolbars\ScreenLayoutTextToolbarOperations.pas',
  ScreenLayoutLineStyleControls in 'Source\Shell\Toolbars\ScreenLayoutLineStyleControls.pas',
  ScreenLayoutCanvasSettingsDialog in 'Source\Shell\ScreenLayoutCanvasSettingsDialog.pas',
  ScreenLayoutProjectiveTransform in 'Source\Core\Geometry\ScreenLayoutProjectiveTransform.pas',
  ScreenLayoutTransformInteraction in 'Source\Editor\Interaction\Transform\ScreenLayoutTransformInteraction.pas',
  ScreenLayoutDocument in 'Source\Core\Model\ScreenLayoutDocument.pas',
  ScreenLayoutPaintStyles in 'Source\Core\Model\ScreenLayoutPaintStyles.pas',
  ScreenLayoutTextureInteraction in 'Source\Editor\Interaction\Texture\ScreenLayoutTextureInteraction.pas',
  ScreenLayoutTextureStyle in 'Source\Core\Model\ScreenLayoutTextureStyle.pas',
  ScreenLayoutPatternStyle in 'Source\Core\Model\Pattern\ScreenLayoutPatternStyle.pas',
  ScreenLayoutPatternRenderer in 'Source\Rendering\Paint\Pattern\ScreenLayoutPatternRenderer.pas',
  ScreenLayoutPatternJson in 'Source\Persistence\ScreenLayoutPatternJson.pas',
  ScreenLayoutPatternControl in 'Source\ObjectProperties\Color\Pattern\ScreenLayoutPatternControl.pas',
  ScreenLayoutPatternControlRenderer in 'Source\ObjectProperties\Color\Pattern\ScreenLayoutPatternControlRenderer.pas',
  ScreenLayoutPaintStyleGesture in 'Source\ObjectProperties\Color\Pattern\ScreenLayoutPaintStyleGesture.pas',
  ScreenLayoutTextureRenderer in 'Source\Rendering\Paint\ScreenLayoutTextureRenderer.pas',
  ScreenLayoutTextureJson in 'Source\Persistence\ScreenLayoutTextureJson.pas',
  ScreenLayoutTextureControl in 'Source\ObjectProperties\Color\Texture\ScreenLayoutTextureControl.pas',
  ScreenLayoutPaintModeSelector in 'Source\ObjectProperties\Color\ScreenLayoutPaintModeSelector.pas',
  ScreenLayoutColorTargetSelector in 'Source\ObjectProperties\Color\ScreenLayoutColorTargetSelector.pas',
  ScreenLayoutTextureDropTarget in 'Source\ObjectProperties\Color\Texture\ScreenLayoutTextureDropTarget.pas',
  ScreenLayoutTextDecompositionCommands in 'Source\Core\Commands\Text\ScreenLayoutTextDecompositionCommands.pas',
  ScreenLayoutFilters in 'Source\Core\Model\ScreenLayoutFilters.pas',
  ScreenLayoutGeometry in 'Source\Core\Geometry\ScreenLayoutGeometry.pas',
  ScreenLayoutEllipseGeometry in 'Source\Core\Geometry\Shape\ScreenLayoutEllipseGeometry.pas',
  ScreenLayoutTextGeometry in 'Source\Core\Geometry\Text\ScreenLayoutTextGeometry.pas',
  ScreenLayoutTextPathGeometry in 'Source\Core\Geometry\Text\ScreenLayoutTextPathGeometry.pas',
  ScreenLayoutTextOutlineGeometry in 'Source\Core\Geometry\Text\ScreenLayoutTextOutlineGeometry.pas',
  ScreenLayoutPathOperations in 'Source\Core\Geometry\Shape\ScreenLayoutPathOperations.pas',
  ScreenLayoutShapeOperations in 'Source\Core\Geometry\Shape\ScreenLayoutShapeOperations.pas',
  ScreenLayoutShapeBooleanGeometry in 'Source\Core\Geometry\Shape\ScreenLayoutShapeBooleanGeometry.pas',
  ScreenLayoutStrokeOutlineGeometry in 'Source\Core\Geometry\Shape\ScreenLayoutStrokeOutlineGeometry.pas',
  ScreenLayoutShapeBooleanOperations in 'Source\Core\Geometry\Shape\ScreenLayoutShapeBooleanOperations.pas',
  ScreenLayoutLayerGeometry in 'Source\Core\Geometry\ScreenLayoutLayerGeometry.pas',
  ScreenLayoutRenderer in 'Source\Rendering\ScreenLayoutRenderer.pas',
  ScreenLayoutCanvasRenderCache in 'Source\Rendering\Cache\ScreenLayoutCanvasRenderCache.pas',
  ScreenLayoutPaintRenderer in 'Source\Rendering\Paint\ScreenLayoutPaintRenderer.pas',
  ScreenLayoutVariableWidthRenderer in 'Source\Rendering\Paint\ScreenLayoutVariableWidthRenderer.pas',
  ScreenLayoutStrokeSampling in 'Source\Rendering\Paint\Stroke\ScreenLayoutStrokeSampling.pas',
  ScreenLayoutCanvasGuides in 'Source\Rendering\ScreenLayoutCanvasGuides.pas',
  ScreenLayoutCanvasPreview in 'Source\Rendering\ScreenLayoutCanvasPreview.pas',
  ScreenLayoutOverlayPrimitives in 'Source\Rendering\Overlay\ScreenLayoutOverlayPrimitives.pas',
  ScreenLayoutOverlayShapes in 'Source\Rendering\Overlay\ScreenLayoutOverlayShapes.pas',
  ScreenLayoutOverlayHandles in 'Source\Rendering\Overlay\ScreenLayoutOverlayHandles.pas',
  ScreenLayoutGradientOverlay in 'Source\Rendering\Overlay\ScreenLayoutGradientOverlay.pas',
  ScreenLayoutTextEditOverlay in 'Source\Rendering\ScreenLayoutTextEditOverlay.pas',
  ScreenLayoutShapePath in 'Source\Rendering\ScreenLayoutShapePath.pas',
  ScreenLayoutContext in 'Source\Core\Model\ScreenLayoutContext.pas',
  ScreenLayoutEditorState in 'Source\Core\Model\ScreenLayoutEditorState.pas',
  ScreenLayoutEditCommands in 'Source\Core\Commands\ScreenLayoutEditCommands.pas',
  ScreenLayoutShapeEditCommands in 'Source\Core\Commands\Shape\ScreenLayoutShapeEditCommands.pas',
  ScreenLayoutShapeBooleanCommands in 'Source\Core\Commands\Shape\ScreenLayoutShapeBooleanCommands.pas',
  ScreenLayoutStrokeOutlineCommands in 'Source\Core\Commands\Shape\ScreenLayoutStrokeOutlineCommands.pas',
  ScreenLayoutTextCommands in 'Source\Core\Commands\Text\ScreenLayoutTextCommands.pas',
  ScreenLayoutLayerStructureCommands in 'Source\Core\Commands\Layer\ScreenLayoutLayerStructureCommands.pas',
  ScreenLayoutLayerBatchCommands in 'Source\Core\Commands\Layer\ScreenLayoutLayerBatchCommands.pas',
  ScreenLayoutGroupCommands in 'Source\Core\Commands\Layer\ScreenLayoutGroupCommands.pas',
  ScreenLayoutGroupChildCommands in 'Source\Core\Commands\Layer\ScreenLayoutGroupChildCommands.pas',
  ScreenLayoutGroupTransformCommands in 'Source\Core\Commands\Layer\ScreenLayoutGroupTransformCommands.pas',
  ScreenLayoutLayerFlipOperations in 'Source\Core\Commands\Layer\ScreenLayoutLayerFlipOperations.pas',
  ScreenLayoutLayerArrangementOperations in 'Source\Core\Commands\Layer\ScreenLayoutLayerArrangementOperations.pas',
  ScreenLayoutLayerTransformCommands in 'Source\Core\Commands\Layer\ScreenLayoutLayerTransformCommands.pas',
  ScreenLayoutFilterCommands in 'Source\Core\Commands\ScreenLayoutFilterCommands.pas',
  ScreenLayoutPaintCommands in 'Source\Core\Commands\ScreenLayoutPaintCommands.pas',
  ScreenLayoutEditHistory in 'Source\Core\Model\ScreenLayoutEditHistory.pas',
  ScreenLayoutDocumentJson in 'Source\Persistence\ScreenLayoutDocumentJson.pas',
  ScreenLayoutDocumentJsonReader in 'Source\Persistence\ScreenLayoutDocumentJsonReader.pas',
  ScreenLayoutDocumentJsonWriter in 'Source\Persistence\ScreenLayoutDocumentJsonWriter.pas',
  ScreenLayoutCanvas in 'Source\Editor\ScreenLayoutCanvas.pas',
  ScreenLayoutCanvasInteraction in 'Source\Editor\Interaction\ScreenLayoutCanvasInteraction.pas',
  ScreenLayoutSnapGeometry in 'Source\Core\Geometry\ScreenLayoutSnapGeometry.pas',
  ScreenLayoutTextPathCharacterInteraction in
    'Source\Editor\Interaction\Text\ScreenLayoutTextPathCharacterInteraction.pas',
  ScreenLayoutContextMenuInteraction in 'Source\Editor\Interaction\ScreenLayoutContextMenuInteraction.pas',
  ScreenLayoutFilterInteraction in 'Source\Editor\Interaction\Filter\ScreenLayoutFilterInteraction.pas',
  ScreenLayoutGradientInteraction in 'Source\Editor\Interaction\Gradient\ScreenLayoutGradientInteraction.pas',
  ScreenLayoutGroupInteraction in 'Source\Editor\Interaction\Group\ScreenLayoutGroupInteraction.pas',
  ScreenLayoutTextEditing in 'Source\Editor\Interaction\Text\ScreenLayoutTextEditing.pas',
  ScreenLayoutInteractionGeometry in 'Source\Editor\Interaction\ScreenLayoutInteractionGeometry.pas',
  ScreenLayoutPathInteraction in 'Source\Editor\Interaction\Shape\ScreenLayoutPathInteraction.pas',
  ScreenLayoutShapeInteraction in 'Source\Editor\Interaction\Shape\ScreenLayoutShapeInteraction.pas',
  ScreenLayoutShapeCreation in 'Source\Editor\Creation\ScreenLayoutShapeCreation.pas',
  ScreenLayoutLayerNaming in 'Source\Editor\Creation\ScreenLayoutLayerNaming.pas',
  ScreenLayoutImageImport in 'Source\Editor\Creation\ScreenLayoutImageImport.pas',
  ScreenLayoutKeyboardMovement in 'Source\Editor\Interaction\ScreenLayoutKeyboardMovement.pas',
  ScreenLayoutEditorWorkspaceFrame in 'Source\Editor\ScreenLayoutEditorWorkspaceFrame.pas',
  ScreenLayoutSelectionGeometry in 'Source\Editor\Interaction\ScreenLayoutSelectionGeometry.pas',
  ScreenLayoutLayerList in 'Source\Layers\ScreenLayoutLayerList.pas',
  ScreenLayoutLayerRenderer in 'Source\Layers\ScreenLayoutLayerRenderer.pas',
  ScreenLayoutLayerActions in 'Source\Layers\ScreenLayoutLayerActions.pas',
  ScreenLayoutLayerOperations in 'Source\Layers\ScreenLayoutLayerOperations.pas',
  ScreenLayoutLayerDuplication in 'Source\Layers\ScreenLayoutLayerDuplication.pas',
  ScreenLayoutLayerPanelFrame in 'Source\Layers\ScreenLayoutLayerPanelFrame.pas',
  ScreenLayoutDockManager in 'Source\Layout\ScreenLayoutDockManager.pas',
  ScreenLayoutToolFrames in 'Source\Layout\ScreenLayoutToolFrames.pas',
  ScreenLayoutObjectPropertiesControl in 'Source\ObjectProperties\ScreenLayoutObjectPropertiesControl.pas',
  ScreenLayoutFilterDetailsFrame in 'Source\ObjectProperties\Filters\ScreenLayoutFilterDetailsFrame.pas',
  ScreenLayoutFilterListControl in 'Source\ObjectProperties\Filters\ScreenLayoutFilterListControl.pas',
  ScreenLayoutFilterFrame in 'Source\ObjectProperties\Filters\ScreenLayoutFilterFrame.pas',
  ScreenLayoutObjectPropertiesFrame in 'Source\ObjectProperties\ScreenLayoutObjectPropertiesFrame.pas',
  ScreenLayoutToolPaletteFrame in 'Source\ToolPalette\ScreenLayoutToolPaletteFrame.pas',
  ScreenLayoutToolPalette in 'Source\ToolPalette\ScreenLayoutToolPalette.pas',
  WindowsImeController in 'Lib\InputMethod\WindowsImeController.pas';

function InitializePlugin(Version: Cardinal): Byte; cdecl;
begin
  InitializeScreenLayoutFilter;
  Result := 1;
end;

procedure UninitializePlugin; cdecl;
begin
  FinalizeScreenLayoutFilter;
end;

function GetFilterPluginTable: PFILTER_PLUGIN_TABLE; cdecl;
begin
  Result := GetScreenLayoutFilterTable;
end;

exports
  InitializePlugin name 'InitializePlugin',
  UninitializePlugin name 'UninitializePlugin',
  GetFilterPluginTable name 'GetFilterPluginTable';

begin
end.
